spring:
  rabbitmq:
    addresses: 47.98.52.193
    username: rabbit
    port: 5672
    password: 123456
    virtual-host: /
    # 实现一个监听器用于监听Broker端给我们返回的确认请求： RabbitTemplate.ConfirmCallBack
    publisher-confirms: true
    # 保证消息对Broker端是可达的，如果出现路由键不可达的情况，
    # 则使用监听器对不可达消息进行后续处理，保证消息路由成功：RabbitTemplate.ReturnCallback
    publisher-returns: true
    # 在发送消息时对template进行配置mandatory=true保证监听有效
    template:
      mandatory: true

    # 消费端
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
      order:
        queue:
          name: queue-2
          durable: true
        exchange:
          name: exchange-1
          durable: true
          type: topic
          ignoreDeclarationExceptions: true
        key: springboot.#